# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: Build
      pool:
        name: 'Azure Pipelines'
      steps:
        - task: CmdLine@2
          inputs:
            script: |
              echo Hello world

  - stage: DEV
    displayName: Deploy to DEV
    jobs:
    - job: DEV
      pool:
        name: 'Azure Pipelines'
      steps:
        - task: CmdLine@2
          inputs:
            script: |
              echo Hello world
