# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  dependsOn: []
  jobs:
    - job: Build
      pool:
        name: 'Azure Pipelines'
      steps:
        - template: ./templates/azure-pipelines-build-template.yml
 
- stage: DEV
  displayName: Deploy to DEV
  jobs:
    - template: ./templates/azure-pipelines-deploy-template.yml
      parameters:
        job_name: deploy_solution
        target_environment: 'DEV'
        variable_group_name: m365_DEV_Configuration
