# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - '*'
    exclude:
      - '**/*.yml'
      - '**/*.yaml'

pool:
  name: 'Azure Pipelines'

variables:
  - group: m365-dev-var-group
  - group: m365-prod-var-group
  - name: node_version
    value: '14.x'
  - name: package_manager
    value: 'npm'
  - name: working_directory
    value: '.'

stages:
- stage: Build
  dependsOn: []
  jobs:
    - template: ./templates/azure-pipelines-build-template.yml
      parameters:
        working_directory: ${{ variables.working_directory }}
        package_manager: ${{ variables.package_manager }}
        node_version: ${{ variables.node_version }}

- stage: DEV
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
    - template: ./templates/azure-pipelines-deploy-template.yml
      parameters:
        display_name: DEV
        target_environment: DEV
        node_version: ${{ variables.node_version }}
