# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: build
    displayName: Build
    jobs:

    - job: Build
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

      pool:
        name: 'Azure Pipelines'
      steps:
        - template: ./templates/azure-pipelines-build-template.yml

  - stage: DEV
    displayName: Deploy to DEV
    jobs:
    - job: DEV
      pool:
        name: 'Azure Pipelines'
      steps:
        - template: ./templates/azure-pipelines-deploy-template.yml
